//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.mcupdater.model.v4;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BaseModuleType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="BaseModuleType">
 *   <complexContent>
 *     <extension base="{http://www.mcupdater.com}DownloadableType">
 *       <sequence>
 *         <element name="LoadPrefix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="ModPath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="Required" type="{http://www.mcupdater.com}RequiredType"/>
 *         <element name="Type" type="{http://www.mcupdater.com}InstallType"/>
 *         <element name="Meta" type="{http://www.mcupdater.com}MetaType" minOccurs="0"/>
 *       </sequence>
 *       <attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="depends" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="side" default="BOTH">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             <enumeration value="BOTH"/>
 *             <enumeration value="CLIENT"/>
 *             <enumeration value="SERVER"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BaseModuleType", propOrder = {
    "loadPrefix",
    "modPath",
    "required",
    "type",
    "meta"
})
@XmlSeeAlso({
    ModuleType.class
})
public class BaseModuleType
    extends DownloadableType
{

    @XmlElement(name = "LoadPrefix")
    protected String loadPrefix;
    @XmlElement(name = "ModPath")
    protected String modPath;
    @XmlElement(name = "Required", required = true)
    protected RequiredType required;
    @XmlElement(name = "Type", required = true)
    protected InstallType type;
    @XmlElement(name = "Meta")
    protected MetaType meta;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "depends")
    protected String depends;
    @XmlAttribute(name = "side")
    protected String side;

    /**
     * Gets the value of the loadPrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoadPrefix() {
        return loadPrefix;
    }

    /**
     * Sets the value of the loadPrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoadPrefix(String value) {
        this.loadPrefix = value;
    }

    /**
     * Gets the value of the modPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModPath() {
        return modPath;
    }

    /**
     * Sets the value of the modPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModPath(String value) {
        this.modPath = value;
    }

    /**
     * Gets the value of the required property.
     * 
     * @return
     *     possible object is
     *     {@link RequiredType }
     *     
     */
    public RequiredType getRequired() {
        return required;
    }

    /**
     * Sets the value of the required property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequiredType }
     *     
     */
    public void setRequired(RequiredType value) {
        this.required = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link InstallType }
     *     
     */
    public InstallType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstallType }
     *     
     */
    public void setType(InstallType value) {
        this.type = value;
    }

    /**
     * Gets the value of the meta property.
     * 
     * @return
     *     possible object is
     *     {@link MetaType }
     *     
     */
    public MetaType getMeta() {
        return meta;
    }

    /**
     * Sets the value of the meta property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetaType }
     *     
     */
    public void setMeta(MetaType value) {
        this.meta = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the depends property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepends() {
        return depends;
    }

    /**
     * Sets the value of the depends property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepends(String value) {
        this.depends = value;
    }

    /**
     * Gets the value of the side property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSide() {
        if (side == null) {
            return "BOTH";
        } else {
            return side;
        }
    }

    /**
     * Sets the value of the side property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSide(String value) {
        this.side = value;
    }

}
