//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.mcupdater.model.v4;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DownloadableType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="DownloadableType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="URL" type="{http://www.mcupdater.com}PrioritizedURLType" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="Repository" type="{http://www.mcupdater.com}RepositoryType" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="Hash" type="{http://www.mcupdater.com}HashType" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="Size" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DownloadableType", propOrder = {
    "url",
    "repository",
    "hash",
    "size"
})
@XmlSeeAlso({
    BaseModuleType.class,
    ConfigType.class,
    SimpleDownloadType.class
})
public class DownloadableType {

    @XmlElement(name = "URL")
    protected List<PrioritizedURLType> url;
    @XmlElement(name = "Repository")
    protected List<RepositoryType> repository;
    @XmlElement(name = "Hash")
    protected List<HashType> hash;
    @XmlElement(name = "Size")
    protected Long size;

    /**
     * Gets the value of the url property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the url property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getURL().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PrioritizedURLType }
     * </p>
     * 
     * 
     * @return
     *     The value of the url property.
     */
    public List<PrioritizedURLType> getURL() {
        if (url == null) {
            url = new ArrayList<>();
        }
        return this.url;
    }

    /**
     * Gets the value of the repository property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the repository property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getRepository().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RepositoryType }
     * </p>
     * 
     * 
     * @return
     *     The value of the repository property.
     */
    public List<RepositoryType> getRepository() {
        if (repository == null) {
            repository = new ArrayList<>();
        }
        return this.repository;
    }

    /**
     * Gets the value of the hash property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hash property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getHash().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HashType }
     * </p>
     * 
     * 
     * @return
     *     The value of the hash property.
     */
    public List<HashType> getHash() {
        if (hash == null) {
            hash = new ArrayList<>();
        }
        return this.hash;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSize(Long value) {
        this.size = value;
    }

}
