//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.mcupdater.model.v4;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for InstallType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="InstallType">
 *   <simpleContent>
 *     <extension base="<http://www.mcupdater.com>ModEnum">
 *       <attribute name="inRoot" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       <attribute name="order" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       <attribute name="keepMeta" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       <attribute name="launchArgs" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="jreArgs" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     </extension>
 *   </simpleContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InstallType", propOrder = {
    "value"
})
public class InstallType {

    @XmlValue
    protected ModEnum value;
    @XmlAttribute(name = "inRoot")
    protected Boolean inRoot;
    @XmlAttribute(name = "order")
    protected BigInteger order;
    @XmlAttribute(name = "keepMeta")
    protected Boolean keepMeta;
    @XmlAttribute(name = "launchArgs")
    protected String launchArgs;
    @XmlAttribute(name = "jreArgs")
    protected String jreArgs;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link ModEnum }
     *     
     */
    public ModEnum getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModEnum }
     *     
     */
    public void setValue(ModEnum value) {
        this.value = value;
    }

    /**
     * Gets the value of the inRoot property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInRoot() {
        return inRoot;
    }

    /**
     * Sets the value of the inRoot property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInRoot(Boolean value) {
        this.inRoot = value;
    }

    /**
     * Gets the value of the order property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOrder() {
        return order;
    }

    /**
     * Sets the value of the order property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOrder(BigInteger value) {
        this.order = value;
    }

    /**
     * Gets the value of the keepMeta property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isKeepMeta() {
        return keepMeta;
    }

    /**
     * Sets the value of the keepMeta property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setKeepMeta(Boolean value) {
        this.keepMeta = value;
    }

    /**
     * Gets the value of the launchArgs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLaunchArgs() {
        return launchArgs;
    }

    /**
     * Sets the value of the launchArgs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLaunchArgs(String value) {
        this.launchArgs = value;
    }

    /**
     * Gets the value of the jreArgs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJreArgs() {
        return jreArgs;
    }

    /**
     * Sets the value of the jreArgs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJreArgs(String value) {
        this.jreArgs = value;
    }

}
