//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.mcupdater.model.v4;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * <p>Java class for ModEnum</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="ModEnum">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="Regular"/>
 *     <enumeration value="Library"/>
 *     <enumeration value="Coremod"/>
 *     <enumeration value="Jar"/>
 *     <enumeration value="Extract"/>
 *     <enumeration value="Litemod"/>
 *     <enumeration value="Removal"/>
 *     <enumeration value="Override"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "ModEnum")
@XmlEnum
public enum ModEnum {

    @XmlEnumValue("Regular")
    REGULAR("Regular"),
    @XmlEnumValue("Library")
    LIBRARY("Library"),
    @XmlEnumValue("Coremod")
    COREMOD("Coremod"),
    @XmlEnumValue("Jar")
    JAR("Jar"),
    @XmlEnumValue("Extract")
    EXTRACT("Extract"),
    @XmlEnumValue("Litemod")
    LITEMOD("Litemod"),
    @XmlEnumValue("Removal")
    REMOVAL("Removal"),
    @XmlEnumValue("Override")
    OVERRIDE("Override");
    private final String value;

    ModEnum(String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static ModEnum fromValue(String v) {
        for (ModEnum c: ModEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
