//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.mcupdater.model.v4;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ModPackType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="ModPackType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Page" type="{http://www.mcupdater.com}PageType" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="Server" type="{http://www.mcupdater.com}ServerListType" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="Import" type="{http://www.mcupdater.com}ImportType" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="Loader" type="{http://www.mcupdater.com}LoaderType" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="Module" type="{http://www.mcupdater.com}ModuleType" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="Resourcepack" type="{http://www.mcupdater.com}SimpleDownloadType" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="Datapack" type="{http://www.mcupdater.com}SimpleDownloadType" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="Shaderpack" type="{http://www.mcupdater.com}SimpleDownloadType" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *       <attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="abstract" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       <attribute name="upstreamUrl" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       <attribute name="upstreamId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="iconUrl" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       <attribute name="mcVersion" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="revision" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="mainClass" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="launcherType" type="{http://www.w3.org/2001/XMLSchema}string" default="Vanilla" />
 *       <attribute name="serverClass" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       <attribute name="libOverrides" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModPackType", propOrder = {
    "page",
    "server",
    "_import",
    "loader",
    "module",
    "resourcepack",
    "datapack",
    "shaderpack"
})
public class ModPackType {

    @XmlElement(name = "Page")
    protected List<PageType> page;
    @XmlElement(name = "Server")
    protected List<ServerListType> server;
    @XmlElement(name = "Import")
    protected List<ImportType> _import;
    @XmlElement(name = "Loader")
    protected List<LoaderType> loader;
    @XmlElement(name = "Module")
    protected List<ModuleType> module;
    @XmlElement(name = "Resourcepack")
    protected List<SimpleDownloadType> resourcepack;
    @XmlElement(name = "Datapack")
    protected List<SimpleDownloadType> datapack;
    @XmlElement(name = "Shaderpack")
    protected List<SimpleDownloadType> shaderpack;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "abstract")
    protected Boolean _abstract;
    @XmlAttribute(name = "upstreamUrl")
    @XmlSchemaType(name = "anyURI")
    protected String upstreamUrl;
    @XmlAttribute(name = "upstreamId")
    protected String upstreamId;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "iconUrl")
    @XmlSchemaType(name = "anyURI")
    protected String iconUrl;
    @XmlAttribute(name = "mcVersion", required = true)
    protected String mcVersion;
    @XmlAttribute(name = "revision", required = true)
    protected String revision;
    @XmlAttribute(name = "mainClass")
    protected String mainClass;
    @XmlAttribute(name = "launcherType")
    protected String launcherType;
    @XmlAttribute(name = "serverClass")
    protected String serverClass;
    @XmlAttribute(name = "libOverrides")
    protected String libOverrides;

    /**
     * Gets the value of the page property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the page property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getPage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PageType }
     * </p>
     * 
     * 
     * @return
     *     The value of the page property.
     */
    public List<PageType> getPage() {
        if (page == null) {
            page = new ArrayList<>();
        }
        return this.page;
    }

    /**
     * Gets the value of the server property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the server property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getServer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ServerListType }
     * </p>
     * 
     * 
     * @return
     *     The value of the server property.
     */
    public List<ServerListType> getServer() {
        if (server == null) {
            server = new ArrayList<>();
        }
        return this.server;
    }

    /**
     * Gets the value of the import property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the import property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getImport().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ImportType }
     * </p>
     * 
     * 
     * @return
     *     The value of the import property.
     */
    public List<ImportType> getImport() {
        if (_import == null) {
            _import = new ArrayList<>();
        }
        return this._import;
    }

    /**
     * Gets the value of the loader property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the loader property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getLoader().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LoaderType }
     * </p>
     * 
     * 
     * @return
     *     The value of the loader property.
     */
    public List<LoaderType> getLoader() {
        if (loader == null) {
            loader = new ArrayList<>();
        }
        return this.loader;
    }

    /**
     * Gets the value of the module property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the module property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getModule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ModuleType }
     * </p>
     * 
     * 
     * @return
     *     The value of the module property.
     */
    public List<ModuleType> getModule() {
        if (module == null) {
            module = new ArrayList<>();
        }
        return this.module;
    }

    /**
     * Gets the value of the resourcepack property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resourcepack property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getResourcepack().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimpleDownloadType }
     * </p>
     * 
     * 
     * @return
     *     The value of the resourcepack property.
     */
    public List<SimpleDownloadType> getResourcepack() {
        if (resourcepack == null) {
            resourcepack = new ArrayList<>();
        }
        return this.resourcepack;
    }

    /**
     * Gets the value of the datapack property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the datapack property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getDatapack().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimpleDownloadType }
     * </p>
     * 
     * 
     * @return
     *     The value of the datapack property.
     */
    public List<SimpleDownloadType> getDatapack() {
        if (datapack == null) {
            datapack = new ArrayList<>();
        }
        return this.datapack;
    }

    /**
     * Gets the value of the shaderpack property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the shaderpack property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getShaderpack().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimpleDownloadType }
     * </p>
     * 
     * 
     * @return
     *     The value of the shaderpack property.
     */
    public List<SimpleDownloadType> getShaderpack() {
        if (shaderpack == null) {
            shaderpack = new ArrayList<>();
        }
        return this.shaderpack;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the abstract property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAbstract() {
        return _abstract;
    }

    /**
     * Sets the value of the abstract property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAbstract(Boolean value) {
        this._abstract = value;
    }

    /**
     * Gets the value of the upstreamUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpstreamUrl() {
        return upstreamUrl;
    }

    /**
     * Sets the value of the upstreamUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpstreamUrl(String value) {
        this.upstreamUrl = value;
    }

    /**
     * Gets the value of the upstreamId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpstreamId() {
        return upstreamId;
    }

    /**
     * Sets the value of the upstreamId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpstreamId(String value) {
        this.upstreamId = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the iconUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIconUrl() {
        return iconUrl;
    }

    /**
     * Sets the value of the iconUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIconUrl(String value) {
        this.iconUrl = value;
    }

    /**
     * Gets the value of the mcVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMcVersion() {
        return mcVersion;
    }

    /**
     * Sets the value of the mcVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMcVersion(String value) {
        this.mcVersion = value;
    }

    /**
     * Gets the value of the revision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRevision() {
        return revision;
    }

    /**
     * Sets the value of the revision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRevision(String value) {
        this.revision = value;
    }

    /**
     * Gets the value of the mainClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMainClass() {
        return mainClass;
    }

    /**
     * Sets the value of the mainClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMainClass(String value) {
        this.mainClass = value;
    }

    /**
     * Gets the value of the launcherType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLauncherType() {
        if (launcherType == null) {
            return "Vanilla";
        } else {
            return launcherType;
        }
    }

    /**
     * Sets the value of the launcherType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLauncherType(String value) {
        this.launcherType = value;
    }

    /**
     * Gets the value of the serverClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServerClass() {
        return serverClass;
    }

    /**
     * Sets the value of the serverClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServerClass(String value) {
        this.serverClass = value;
    }

    /**
     * Gets the value of the libOverrides property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLibOverrides() {
        return libOverrides;
    }

    /**
     * Sets the value of the libOverrides property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLibOverrides(String value) {
        this.libOverrides = value;
    }

}
