//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.mcupdater.model.v4;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ModuleType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="ModuleType">
 *   <complexContent>
 *     <extension base="{http://www.mcupdater.com}BaseModuleType">
 *       <sequence>
 *         <element name="Submodule" type="{http://www.mcupdater.com}BaseModuleType" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="ConfigFile" type="{http://www.mcupdater.com}ConfigType" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModuleType", propOrder = {
    "submodule",
    "configFile"
})
public class ModuleType
    extends BaseModuleType
{

    @XmlElement(name = "Submodule")
    protected List<BaseModuleType> submodule;
    @XmlElement(name = "ConfigFile")
    protected List<ConfigType> configFile;

    /**
     * Gets the value of the submodule property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the submodule property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getSubmodule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BaseModuleType }
     * </p>
     * 
     * 
     * @return
     *     The value of the submodule property.
     */
    public List<BaseModuleType> getSubmodule() {
        if (submodule == null) {
            submodule = new ArrayList<>();
        }
        return this.submodule;
    }

    /**
     * Gets the value of the configFile property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the configFile property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getConfigFile().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConfigType }
     * </p>
     * 
     * 
     * @return
     *     The value of the configFile property.
     */
    public List<ConfigType> getConfigFile() {
        if (configFile == null) {
            configFile = new ArrayList<>();
        }
        return this.configFile;
    }

}
