//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.mcupdater.model.v4;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.mcupdater.model.jaxb package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.mcupdater.model.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ServerPack }
     * 
     * @return
     *     the new instance of {@link ServerPack }
     */
    public ServerPack createServerPack() {
        return new ServerPack();
    }

    /**
     * Create an instance of {@link ModPackType }
     * 
     * @return
     *     the new instance of {@link ModPackType }
     */
    public ModPackType createModPackType() {
        return new ModPackType();
    }

    /**
     * Create an instance of {@link ServerListType }
     * 
     * @return
     *     the new instance of {@link ServerListType }
     */
    public ServerListType createServerListType() {
        return new ServerListType();
    }

    /**
     * Create an instance of {@link PageType }
     * 
     * @return
     *     the new instance of {@link PageType }
     */
    public PageType createPageType() {
        return new PageType();
    }

    /**
     * Create an instance of {@link ImportType }
     * 
     * @return
     *     the new instance of {@link ImportType }
     */
    public ImportType createImportType() {
        return new ImportType();
    }

    /**
     * Create an instance of {@link LoaderType }
     * 
     * @return
     *     the new instance of {@link LoaderType }
     */
    public LoaderType createLoaderType() {
        return new LoaderType();
    }

    /**
     * Create an instance of {@link ModuleType }
     * 
     * @return
     *     the new instance of {@link ModuleType }
     */
    public ModuleType createModuleType() {
        return new ModuleType();
    }

    /**
     * Create an instance of {@link BaseModuleType }
     * 
     * @return
     *     the new instance of {@link BaseModuleType }
     */
    public BaseModuleType createBaseModuleType() {
        return new BaseModuleType();
    }

    /**
     * Create an instance of {@link ConfigType }
     * 
     * @return
     *     the new instance of {@link ConfigType }
     */
    public ConfigType createConfigType() {
        return new ConfigType();
    }

    /**
     * Create an instance of {@link InstallType }
     * 
     * @return
     *     the new instance of {@link InstallType }
     */
    public InstallType createInstallType() {
        return new InstallType();
    }

    /**
     * Create an instance of {@link RequiredType }
     * 
     * @return
     *     the new instance of {@link RequiredType }
     */
    public RequiredType createRequiredType() {
        return new RequiredType();
    }

    /**
     * Create an instance of {@link SimpleDownloadType }
     * 
     * @return
     *     the new instance of {@link SimpleDownloadType }
     */
    public SimpleDownloadType createSimpleDownloadType() {
        return new SimpleDownloadType();
    }

    /**
     * Create an instance of {@link DownloadableType }
     * 
     * @return
     *     the new instance of {@link DownloadableType }
     */
    public DownloadableType createDownloadableType() {
        return new DownloadableType();
    }

    /**
     * Create an instance of {@link PrioritizedURLType }
     * 
     * @return
     *     the new instance of {@link PrioritizedURLType }
     */
    public PrioritizedURLType createPrioritizedURLType() {
        return new PrioritizedURLType();
    }

    /**
     * Create an instance of {@link RepositoryType }
     * 
     * @return
     *     the new instance of {@link RepositoryType }
     */
    public RepositoryType createRepositoryType() {
        return new RepositoryType();
    }

    /**
     * Create an instance of {@link HashType }
     * 
     * @return
     *     the new instance of {@link HashType }
     */
    public HashType createHashType() {
        return new HashType();
    }

    /**
     * Create an instance of {@link MetaType }
     * 
     * @return
     *     the new instance of {@link MetaType }
     */
    public MetaType createMetaType() {
        return new MetaType();
    }

}
